using System;
using System.Collections.Generic;
using System.Linq;
using Npgsql;

namespace MiniOrm.Data;
/*
 It uses the metadata generated by the TypeMapper to dynamically build safe, parameterized SQL queries
 */
public class DbSet<T> where T : class, new()
{
    private readonly DbContext _context;
    private readonly EntityMetadata _metadata;

    public DbSet(DbContext context)
    {
        _context = context;
        _metadata = TypeMapper.GetMetadata(typeof(T));
    }

    // 1. CREATE
    public int Insert(T entity)
    {
        var insertCols = _metadata.Columns.Where(c => !c.IsPrimaryKey).ToList();
        
        var colNames = string.Join(", ", insertCols.Select(c => c.ColumnName));
        var paramNames = string.Join(", ", insertCols.Select(c => "@" + c.ColumnName));
        
        string sql = $"INSERT INTO {_metadata.TableName} ({colNames}) VALUES ({paramNames}) RETURNING {_metadata.PrimaryKey.ColumnName};";

        using var cmd = new NpgsqlCommand(sql, _context.Connection);
        
        foreach (var col in insertCols)
        {
            var value = col.Property.GetValue(entity);
            cmd.Parameters.AddWithValue("@" + col.ColumnName, value ?? DBNull.Value);
        }
        
        return Convert.ToInt32(cmd.ExecuteScalar());
    }

    // 2. READ (Single)
    public T? FindById(int id)
    {
        string sql = $"SELECT * FROM {_metadata.TableName} WHERE {_metadata.PrimaryKey.ColumnName} = @id LIMIT 1;";
        
        using var cmd = new NpgsqlCommand(sql, _context.Connection);
        cmd.Parameters.AddWithValue("@id", id);

        using var reader = cmd.ExecuteReader();
        
        if (reader.Read())
        {
            return MapReaderToObject(reader);
        }
        
        return null;
    }

    // 3. READ (All)
    public IEnumerable<T> GetAll()
    {
        var results = new List<T>();
        string sql = $"SELECT * FROM {_metadata.TableName};";
        
        using var cmd = new NpgsqlCommand(sql, _context.Connection);
        using var reader = cmd.ExecuteReader();

        while (reader.Read())
        {
            results.Add(MapReaderToObject(reader));
        }

        return results;
    }

    // 4. UPDATE
    public void Update(T entity)
    {
        var updateCols = _metadata.Columns.Where(c => !c.IsPrimaryKey).ToList();
        
        var setClause = string.Join(", ", updateCols.Select(c => $"{c.ColumnName} = @{c.ColumnName}"));
        
        string sql = $"UPDATE {_metadata.TableName} SET {setClause} WHERE {_metadata.PrimaryKey.ColumnName} = @id;";

        using var cmd = new NpgsqlCommand(sql, _context.Connection);
        
        foreach (var col in updateCols)
        {
            var value = col.Property.GetValue(entity);
            cmd.Parameters.AddWithValue("@" + col.ColumnName, value ?? DBNull.Value);
        }
        
        var pkValue = _metadata.PrimaryKey.Property.GetValue(entity);
        cmd.Parameters.AddWithValue("@id", pkValue!);
        
        cmd.ExecuteNonQuery();
    }

    // 5. DELETE
    public void Delete(int id)
    {
        string sql = $"DELETE FROM {_metadata.TableName} WHERE {_metadata.PrimaryKey.ColumnName} = @id;";
        
        using var cmd = new NpgsqlCommand(sql, _context.Connection);
        cmd.Parameters.AddWithValue("@id", id);
        
        cmd.ExecuteNonQuery();
    }
    
    private T MapReaderToObject(NpgsqlDataReader reader)
    {
        
        var entity = new T();

        foreach (var col in _metadata.Columns)
        {
            
            var dbValue = reader[col.ColumnName];

           
            if (dbValue != DBNull.Value)
            {
                col.Property.SetValue(entity, dbValue);
            }
        }

        return entity;
    }
}